# Basic Configuration
baseurl = "https://jfreedman.org" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Joe Freedman"
title = "Joe Freedman"

theme = "hugo-goa"

# Hugo Built-in Features
googleAnalytics = "UA-120052648-1"
enableRobotsTXT = true

## Site Settings
[params]
    author = "Joe Freedman"
    intro = "Computer Science Graduate Student"
    description = "at Michigan State University"
    authorimage = "joe-square.jpg"
    dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
    description = "Joe Freedman Personal Site"
    keywords = "minimalist,blog,goa,hugo,developer,joe,freedman,personal,site,msu,michigan,state"

## Social Accounts
[params.social]
    github = "jfreedman0"
    linkedin = "jfreedman0"
    # medium = "@jfreedman0"
    resume = "jf_resume"

## Extras
[params.extra]
    copyright = "Â© Joe Freedman 2018" 
    poweredby = true
    highlightjs = true

## Main Menu
[[menu.main]]
    name = ""
